export const TIME_SLIDER_HOURS = 22;
export const TIME_SLIDER_AFTER_HOURS = 5;
export const MINTUES_IN_HOUR = 60;
export const TIME_SLIDER_MIN_HOUR = TIME_SLIDER_AFTER_HOURS * MINTUES_IN_HOUR;
export const TIME_SLIDER_MAX_HOUR = (TIME_SLIDER_AFTER_HOURS + TIME_SLIDER_HOURS) * MINTUES_IN_HOUR;